# Generated by Django 5.0.4 on 2024-05-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=25)),
                ('booking_date', models.DateField(max_length=8, null=True)),
                ('booking_time', models.TimeField(max_length=4, null=True)),
                ('address', models.CharField(max_length=150)),
                ('allergies', models.CharField(default='No Allergies Stated', max_length=150)),
                ('booking_size', models.IntegerField(null=True)),
                ('additional_requests', models.CharField(default='No Additional Request', max_length=600)),
            ],
        ),
    ]
