# Generated by Django 5.0.4 on 2024-05-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_user_alter_booking_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='additional_requests',
            new_name='requests',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='allergies',
        ),
        migrations.AddField(
            model_name='booking',
            name='dietary_requirements',
            field=models.CharField(default='No Dietary Requirements/Allergies Stated', max_length=150),
        ),
    ]
