# Generated by Django 5.0.4 on 2024-05-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_booking_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='additional_requests',
            field=models.CharField(default='No Additional Request', max_length=600),
        ),
    ]
