# Generated by Django 3.2.25 on 2024-04-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20240411_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='booking',
            name='allergies',
            field=models.CharField(default='No Allergies', max_length=150),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default='', max_length=8),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
